# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20150707_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_pt_br',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='long_text_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='long_text_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='long_text_pt_br',
        ),
        migrations.RemoveField(
            model_name='category',
            name='long_text_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_pt_br',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='short_name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='short_name_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='short_name_pt_br',
        ),
        migrations.RemoveField(
            model_name='category',
            name='short_name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_pt_br',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long_name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long_name_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long_name_pt_br',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long_name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long_text_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long_text_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long_text_pt_br',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long_text_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_pt_br',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_title_en',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_title_es',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_title_pt_br',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_title_ru',
        ),
        migrations.RemoveField(
            model_name='shopimage',
            name='image_title_en',
        ),
        migrations.RemoveField(
            model_name='shopimage',
            name='image_title_es',
        ),
        migrations.RemoveField(
            model_name='shopimage',
            name='image_title_pt_br',
        ),
        migrations.RemoveField(
            model_name='shopimage',
            name='image_title_ru',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description_pt_br',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='long_text_en',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='long_text_es',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='long_text_pt_br',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='long_text_ru',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_pt_br',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_ru',
        ),
    ]
